#pragma once
#include <Windows.h>

extern "C" {

	LONG NTAPI DetourNtOpenProcess(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES, CLIENT_ID*);
	LONG NTAPI DetourNtCreateThreadEx(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES, HANDLE, PVOID, PVOID, ULONG, SIZE_T, SIZE_T, SIZE_T, PVOID);
	LONG NTAPI DetourNtWriteVirtualMemory(HANDLE, PVOID, PVOID, ULONG, PULONG);
	LONG NTAPI DetourNtReadVirtualMemory(HANDLE, PVOID, PVOID, ULONG, PULONG);
	LONG NTAPI DetourNtAllocateVirtualMemory(HANDLE, PVOID*, ULONG, PSIZE_T, ULONG, ULONG);
	LONG NTAPI DetourNtMapViewOfSection(HANDLE, HANDLE, PVOID*, ULONG_PTR, SIZE_T, PLARGE_INTEGER, PSIZE_T, DWORD, ULONG, ULONG);

	extern LONG(NTAPI* OriginalNtOpenProcess)(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES, CLIENT_ID*);
	extern LONG(NTAPI* OriginalNtCreateThreadEx)(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES, HANDLE, PVOID, PVOID, ULONG, SIZE_T, SIZE_T, SIZE_T, PVOID);
	extern LONG(NTAPI* OriginalNtWriteVirtualMemory)(HANDLE, PVOID, PVOID, ULONG, PULONG);
	extern LONG(NTAPI* OriginalNtReadVirtualMemory)(HANDLE, PVOID, PVOID, ULONG, PULONG);
	extern LONG(NTAPI* OriginalNtAllocateVirtualMemory)(HANDLE, PVOID*, ULONG, PSIZE_T, ULONG, ULONG);
	extern LONG(NTAPI* OriginalNtMapViewOfSection)(HANDLE, HANDLE, PVOID*, ULONG_PTR, SIZE_T, PLARGE_INTEGER, PSIZE_T, DWORD, ULONG, ULONG);

}
